FROM packpack/packpack:fedora-rawhide
# Plover dependencies.
RUN dnf -y install \
	    python-qt5 \
	    python3 \
	    python3-appdirs \
	    python3-babel \
	    python3-devel \
	    python3-docopt \
	    python3-hidapi \
	    python3-mock \
	    python3-pyserial \
	    python3-pytest \
	    python3-pytz \
	    python3-qt5 \
	    python3-setuptools \
	    python3-setuptools_scm \
	    python3-wcwidth \
	    python3-xlib \
	    ;
